### ISSUE TITLE
Trim anonymous classes from classname

### ISSUE THREAD

**Issue by h4ste** [pmwmedia/tinylog#10]
I don't know how to tag this as a feature request and not a bug, but I was wondering if it would be possible to trim or remove the anonymous class portion from the classname written by the logger?

For example, 

In tinylog.writer1.format I have:
tinylog.writer1.format = {date:hh:mm:ss.SSS} | {level} | {class}: {message}

In my source file, WikiParser I use extensive logging using some java 8 streams and junk. Unfortunately, the messages are formatted as:
03:45:54.177 | INFO | edu.utdallas.hltri.copa.wiki.WikiParser$$anonfun$2$$anonfun$apply$2$$anonfun$apply$4$$anonfun$apply$6$$anonfun$apply$8$$anonfun$apply$10: [Parsing XML] Saved "Mekong"

What I would like to see:
03:45:54.177 | INFO | edu.utdallas.hltri.copa.wiki.WikiParser: [Parsing XML] Saved "Mekong"

It seems, naively, that it might be as simple as triming everything in the classpath after (and including) the first '$'. I would have done this myself, but I can't figure out how to implement a custom format and I can't override the existing behavior because everything is final.

**Comment by pmwmedia** [comment]
comprehensible feature request, it is on the to-do list
