### ISSUE TITLE
Run Checkstyle and FindBugs via Travis CI

### ISSUE THREAD

**Issue by pmwmedia** [pmwmedia/tinylog#18]
The existing Checkstyle and FindBugs checks should be applied in the Travis CI script out of the box to all projects but the parent project.

**Comment by pmwmedia** [comment]
Fixed by commit bff8157

**Comment by boldtrn** [comment]
Just found this commit and tried this myself. findbugs:findbugs and checkstyle:checkstyle don't fail the build. If you use findbugs:check it will fail the build.

Here is a random violation that you can copy in your code to test this. You travis build won't fail with findbugs:fingubgs:
```
    private static Boolean inited = Boolean.FALSE;

    public int hashcode() {
        synchronized(inited) {
            if (!inited) {
                inited = Boolean.TRUE;
            }
        }
        int hash = 5;
        return hash;
    }
```

**Comment by pmwmedia** [comment]
Thanks for the note! You are right. I reopened the issue.

**Comment by boldtrn** [comment]
I have just seen your latest commit. As a side node. This will slow down your regular execution of `mvn clean test verify`, that's why we moved it to only run on travis.

**Comment by pmwmedia** [comment]
Yes, it slows down building tinylog a bit. But Checkstyle and Findbugs are faster than the JUnit tests and I want to ensure that there are no violations before committing.
