### ISSUE TITLE
bug in 1.0 branch w/ sfl4j: fixed

### ISSUE THREAD

**Issue by vicApakau** [pmwmedia/tinylog#25]
I was getting error getMDCA  not found in your StaticMDCBinder class.

- public NOPMDCAdapter getMDCA() {
+ public MDCAdapter getMDCA() {

and joy.
Still love your lib.
Cheers,
Vic

**Comment by pmwmedia** [comment]
Fixed in c9f1f89cbf708d59e67095fe724fd2d2db5ddd88. Patch will be released soon.

**Comment by pmwmedia** [comment]
I have just released tinylog 1.0.3, which includes the fix. In my example application, MDC is working in conjunction with SLF4J now. Can you test, too? Please let me know whether is working for you.

**Comment by pmwmedia** [comment]
Issue creator has confirmed that the bug fix is working.
