### ISSUE TITLE
Unknown value type: "CONTEXT"

### ISSUE THREAD

**Issue by Aur0r** [pmwmedia/tinylog#27]
Hi tinylog-creators,
with the jdbc configuation below I get the following output:
LOGGER WARNING: Unknown value type: "CONTEXT"
LOGGER ERROR: Failed to activate configuration (java.sql.SQLException: Number of columns and values must be equal, but columns = 8 and values = 7)

JDBC config:
tinylog.writer = jdbc
tinylog.writer.url = jdbc:mysql://localhost:3306/&lt;db_name&gt;
tinylog.writer.table = log_entries_table
tinylog.writer.columns = context, level, message, class, line, date, method, exception
tinylog.writer.values = CONTEXT, LEVEL, MESSAGE, CLASS, LINE, DATE, METHOD, EXCEPTION

For the context column I took a text datatype in the database (MySQL).

Everything other than CONTEXT works fine. How can I make this work?

Best regards

**Comment by pmwmedia** [comment]
Fixed by commit 7bbe3ab99ce917b804836cc7f0c7d8ef5a7bd877 and released as tinylog 1.1-rc2. Can you confirm that the fix works in your environment, too?

**Comment by Aur0r** [comment]
Very nice! Thank you @pmwmedia! Yes it works for me as well :)
