### ISSUE TITLE
Could it be that when the jdbc connection is lost the logger doesn't reconnect?

### ISSUE THREAD

**Issue by Aur0r** [pmwmedia/tinylog#28]
Hi, as the subject already says I have a question about whether the jdbc connection is reestablished automatically after it gets disconnected?

I have experienced that I had to restart my server to get new log data from tinylog although the application has been in use by users in the meantime.

Best regards and thank you for your support

**Comment by Aur0r** [comment]
For detecting such connection losses (if there are some - I am still wondering if that was the problem) you could maybe log that the connection has been lost, so that one as an admin could see that this happened. Another thing would be that an existing connection is provided to tinylog, that can then be managed by the application instead of tinylog having to do this.

**Comment by pmwmedia** [comment]
I agree that it makes sense to reestablish broken JDBC connections. We can add this feature to tinylog 1.2 or 2.0. I propose to have a configurable interval between the tries to reestablish the connection.

**Comment by Aur0r** [comment]
Configurable interval would be perfectly fine :) Thank you!

**Comment by Aur0r** [comment]
I am wondering if JDBC's ?autoreconnect=true command at the end of the url also solves it for now. There are some error when activating the logger then (at least in my installation) but it logs anyway afterwards, so I will just give it a try for now.

**Comment by pmwmedia** [comment]
I have committed it: 7279a07060001e4a90f4fdfd48ad670f07555653. Auto reconnecting has to be enabled by setting "tinylog.writer.reconnect = X". X is the minimum time span between two tries to reestablish a database connection. For example: "30" means that tinylog will wait at least 30 seconds between two tries to reconnect. Negative numbers disable auto reconnecting at all (default). "0" means that tinylog will try to reconnect for every log entry, if the connection is broken. Can you test and verify if  it is working with your environment?

**Comment by Aur0r** [comment]
Thank you! I will try it out next week.
