### ISSUE TITLE
Logger placeholder in the format.

### ISSUE THREAD

**Issue by agilesteel** [pmwmedia/tinylog#5]
Hi,

I have a big project with logback and slf4j and as a first step of converting it to tinylog I didn't want to use the static logger. Using the sfl4j-facade you provided makes it seem like a drop in replacement. The only issue/question I have is when I'm specifying a custom format I need access to the placeholder variable for the "logger":

```
tinylog.format = [{{level}|min-size=7}] [{date:MMMM dd, YYYY HH:mm:ss.SSS z}] [{thread}] [{logger}] {message}\n
```

In case of the static logger I could just go for class, method etc, but it's not a static one, so if I were to use class.method I'd get sth like (I'm using scala btw, but it wasn't an issue with logback etc):

```
net.liftweb.common.Logger$class.warn()
```

To be clear the class you see in there is not mine :)

So is there a way to get to the logger instance? like {logger} or {source} or {src}...

Cheers

**Comment by pmwmedia** [comment]
Hi Vladyslav,

If I understand aright, you need the fully-qualified logger class to make sure which logger has created the log entry?

**Comment by agilesteel** [comment]
Yep :)

**Comment by pmwmedia** [comment]
The use case is understandable, but unfortunately too specific for a lightweight framework as tinylog is. Therefor it will be not part of tinylog 2.0.
