### ISSUE TITLE
Make it possible to define into which file a log entry should go, allowing multiple files at the same time

### ISSUE THREAD

**Issue by degill** [pmwmedia/tinylog#6]
I have a setup where I have two types of logging information. Something like system monitoring and something like session/user monitoring. And I want to log both but seperate the information into two log files.

Is this possible with tiynlog? I looked at RollingFileWriter but that seems to be useful in the case of multiple consecutive and not multiple parallel files.

**Comment by pmwmedia** [comment]
For tinylog 1.1 are planned includes and excludes patterns for logging writers (-> http://www.tinylog.org/roadmap). It will be possible to define packages and class names. Will it help you?

**Comment by degill** [comment]
I think it could help me, depending on the implementation. If the filtering is defined at package/class level than it would not help me. I have classes emitting different types of log messages (status, result, errors, etc.) so I want to redirect those messages into different files depending on the logmessage itself, not by which class it was emitted.

Right now I worked around it and implemented my own writers, which are wrappers (because your classes are final) and which delegate the actual writing to a FileWriter only if a pattern is matched, with each writer having its own pattern.

    public abstract static class FileWriterWrapper implements Writer {

        public final FileWriter WRITER;

        public FileWriterWrapper(String filename) {
            WRITER = new FileWriter(filename, false);
        }

        @Override
        public Set<LogEntryValue> getRequiredLogEntryValues() {
            return WRITER.getRequiredLogEntryValues();
        }

        @Override
        public void init(Configuration configuration) throws Exception {
            WRITER.init(configuration);
        }

        @Override
        public void flush() throws Exception {
            WRITER.flush();
        }

        @Override
        public void close() throws Exception {
            WRITER.close();
        }
    }

and then subclassing that writer to have my filtering:

    private static class FileWriterSystem extends FileWriterWrapper {

        public FileWriterSystem(String filename) {
            super(filename);
        }

        @Override
        public void write(LogEntry logEntry) throws Exception {
            if (condition-matched) {
                    super.WRITER.write(logEntry);
            }
        }
    }

Of course its a bit inconvenient, but it was my first idea and its fine for now.

**Comment by pmwmedia** [comment]
You parse the log message for your condition? I think about a small filter framework for writers. So you have just to implement a filter interface.

    public interface Filter {

        boolean accept(LogEntry logEntry);

    }

Would it helpful for you? I could imagine such a feature for tinylog 2.0. But it depends a bit on the demand.

**Comment by degill** [comment]
Yes, that was actually my initial idea. But I can imagine that would be a performance loss.

**Comment by pmwmedia** [comment]
I'm open for better ideas :-)

**Comment by degill** [comment]
I did not want to say that it was a bad idea :) I just think one should then be careful when using such a filter..Its depending on the usecase, I guess

**Comment by degill** [comment]
I prefered it that way because then the log-emitter (the code executing Logger.*) does not have to think about any filtering.

Another solution could be to explicitly define some kind of a tag/label to a logmessage.

    new FileWriter(..., "system", "user:degill")

to define which FileWriter is responsible for which file and which tags.
Downside: Now the log-caller needs to decide where the log message should go

    Logger.info(message, "user:degill")

**Comment by pmwmedia** [comment]
I like the idea of tags:

    Logger.tag("SYSTEM").info("Hello World");

**Comment by thejeed** [comment]
Hi together, I'd like to add that I'm also just waiting for this particular feature to use tinylog in production. Also, I think that the idea of using tags is a nice solution.

**Comment by pmwmedia** [comment]
Implemented in branch v2.0
