### ISSUE TITLE
Crash when filename contains non-existent directory

### ISSUE THREAD

**Issue by h4ste** [pmwmedia/tinylog#8]
If a file logger's filename contains a directory, creating the logger crashes if that directory does not exist.

For example:

tinylog.writer2 = rollingfile
tinylog.writer2.filename = logs/log.txt
tinylog.writer2.backups = 10

If I run this in a directory which does not yet contain a logs/ folder, the program crashes.

Given that the logfile itself is created at start-up, it seems reasonable that any folders in the filename should also be created.

**Comment by pmwmedia** [comment]
Thanks for reporting! I can reproduce this bug for all file based writers. Will be fixed in the next release!

**Comment by pmwmedia** [comment]
Preview of fixed version: http://www.tinylog.org/downloads/tinylog-1.0.1.zip

**Comment by pmwmedia** [comment]
Fixed in tinylog 1.0.1
