### ISSUE TITLE
NPE on -javaagent

### ISSUE THREAD

**Issue by flashpixx** [pmwmedia/tinylog#9]
On running tinylog with the -javaagent flag a NPE is thrown on the line https://github.com/pmwmedia/tinylog/blob/master/tinylog/src/main/java/org/pmw/tinylog/Logger.java#L45
The init() call cannot be run outside the package

**Comment by pmwmedia** [comment]
I tested it with tinylog 1.0.1 and jmockit as java agent. No NPE has been thrown. I use JDK 1.8.0_45. What version of tinylog and Java do you use? Maybe you can provide a small demo project?

**Comment by flashpixx** [comment]
I have tested the code with the version 1.0.1 (prior 1.0), so 1.0.1 seems to be working fine. Sorry for the issue
